<script setup lang="ts">
import { computed } from 'vue'
import { useData } from 'vitepress'
import { data } from '../media.data'
import type { Media, Tag } from '../media.data'
import { CATEGORY_UI, fill, categoryPath } from '../categories.ts'
import { useLang } from './useLang.ts'

/**
 * Everything the site has of one kind of thing.
 *
 * The four written pages are about what Titania sells. These are about what
 * she does: one page per word in the vocabulary, generated by
 * `[category].paths.ts`, populated by whatever carries that tag. Nobody
 * maintains them — adding a frame adds it to every category page it belongs
 * on, in three languages, and a new category is one word in `TAGS`.
 *
 * Under each picture is where else on the site it appears, which is internal
 * linking the site never had. It comes from the reverse of the placement
 * index, so it cannot go stale: move a figure to another section and the link
 * follows it.
 *
 * ---- weight ---------------------------------------------------------------
 *
 * A listing shows a whole tag at once, and `performance` is a dozen frames. A
 * dozen of the 50 KB pictures the prose uses would be twice the page budget,
 * so this ships the 240px square instead — about 11 KB — and links to the
 * pages where the picture is shown properly, at size, with its text around it.
 */

const { params } = useData()
const { lang } = useLang()

const tag = computed<Tag>(() => (params.value?.category ?? '') as Tag)
const name = computed(() => (params.value?.name ?? '') as string)
const t = computed(() => CATEGORY_UI[lang.value])
const names = computed(() => data.label[lang.value])

const frames = computed<Media[]>(() =>
  data.media.filter((m) => m.tags.includes(tag.value))
)

/** The other categories, so a reader can move sideways rather than back. */
const siblings = computed(() =>
  data.tags
    .filter((other) => other !== tag.value && data.media.some((m) => m.tags.includes(other)))
    .map((other) => ({ tag: other, name: names.value[other], path: categoryPath(lang.value, other) }))
)

const countOf = (n: number) => (n === 1 ? t.value.one : fill(t.value.many, n))
const clock = (s: number) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`
const pagesFor = (m: Media) => (data.usedOn[m.id] ?? []).filter((p) => p.lang === lang.value)
</script>

<template>
  <section class="cat">
    <!-- The h1 is here rather than in the Markdown on purpose. `# {{ $params.name }}`
         renders the right words, but the anchor VitePress builds beside it is
         made from the raw expression: every one of the 39 pages got
         id="params-name" and a permalink reading "Permalink to {{ $params.name }}".
         A heading that comes from data belongs in the component that has the data. -->
    <h1 class="cat__title">{{ name }}</h1>
    <p class="cat__count">{{ countOf(frames.length) }}</p>

    <p v-if="!frames.length" class="cat__empty">{{ t.empty }}</p>

    <ul v-else class="cat__list">
      <li v-for="frame in frames" :key="frame.id" class="cat__item">
        <!-- A film gets a player rather than a still. `preload="none"` means
             it costs the page nothing until somebody presses play, and without
             it a listing could show a film's poster while offering no way
             anywhere on the site to watch it. -->
        <video
          v-if="frame.mp4"
          class="cat__tile"
          :src="frame.mp4"
          :poster="frame.tile"
          :aria-label="frame.alt[lang]"
          controls
          playsinline
          preload="none"
        />
        <img
          v-else
          class="cat__tile"
          :src="frame.tile"
          :alt="frame.alt[lang]"
          width="240"
          height="240"
          loading="lazy"
          decoding="async"
        />
        <div class="cat__words">
          <p class="cat__kind">
            {{ frame.kind === 'video' ? data.ui[lang].video : data.ui[lang].photo
            }}<template v-if="frame.seconds"> · {{ clock(frame.seconds) }}</template>
          </p>
          <p class="cat__caption">{{ frame.caption[lang] }}</p>
          <p v-if="pagesFor(frame).length" class="cat__where">
            {{ t.alsoOn }}
            <a v-for="page in pagesFor(frame)" :key="page.path" :href="page.path">{{ page.title }}</a>
          </p>
          <p class="cat__tags">
            <a
              v-for="other in frame.tags"
              :key="other"
              :href="categoryPath(lang, other)"
              :class="{ 'cat__tag--here': other === tag }"
            >{{ names[other] }}</a>
          </p>
        </div>
      </li>
    </ul>

    <nav v-if="siblings.length" class="cat__siblings" :aria-label="t.indexTitle">
      <a v-for="other in siblings" :key="other.tag" :href="other.path">{{ other.name }}</a>
    </nav>
  </section>
</template>

<style scoped>
.cat { margin: 0; }
.cat__title {
  margin: 0 0 0.6rem;
  font-size: 32px;
  font-weight: 600;
  letter-spacing: -0.035em;
  line-height: 1.08;
  text-wrap: balance;
}
.cat__count {
  margin: 0 0 1.4rem;
  color: var(--vp-c-text-3);
  font-size: 11px;
  font-weight: 700;
  font-variant-numeric: tabular-nums;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}
.cat__empty { color: var(--vp-c-text-2); }

.cat__list { margin: 0; padding: 0; list-style: none; }
.cat__item {
  display: grid;
  grid-template-columns: 7.5rem minmax(0, 1fr);
  gap: 1.1rem;
  align-items: start;
  margin: 0 0 1.6rem;
  padding-bottom: 1.6rem;
  border-bottom: 1px solid var(--vp-c-divider);
}
.cat__item:last-child { border-bottom: 0; }

.cat__tile {
  width: 100%;
  height: auto;
  margin: 0;
  aspect-ratio: 1;
  object-fit: cover;
  border-radius: 10px;
  background: var(--vp-c-bg-soft);
}

.cat__words { min-width: 0; }
.cat__kind {
  margin: 0 0 0.2rem;
  color: var(--vp-c-text-3);
  font-size: 11px;
  font-weight: 700;
  font-variant-numeric: tabular-nums;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}
.cat__caption {
  margin: 0;
  color: var(--vp-c-text-1);
  font-size: 0.9375rem;
  line-height: 1.55;
  text-wrap: pretty;
}
.cat__where { margin: 0.4rem 0 0; color: var(--vp-c-text-2); font-size: 0.8125rem; }
.cat__where a:not(:last-child)::after { content: ','; color: var(--vp-c-text-3); }
.cat__where a { margin-right: 0.35rem; }

.cat__tags { display: flex; flex-wrap: wrap; gap: 0.2rem 0.6rem; margin: 0.45rem 0 0; }
.cat__tags a {
  color: var(--vp-c-text-3);
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.07em;
  text-transform: uppercase;
  text-decoration: none;
}
.cat__tags a:hover { color: var(--vp-c-brand-1); }
/* The category you are already on is not a link worth taking. */
.cat__tag--here { color: var(--vp-c-brand-1) !important; }

.cat__siblings {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-top: 2.5rem;
  padding-top: 1.5rem;
  border-top: 1px solid var(--vp-c-divider);
}
.cat__siblings a {
  padding: 0.3rem 0.75rem;
  border: 1px solid var(--vp-c-divider);
  border-radius: 999px;
  color: var(--vp-c-text-2);
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  text-decoration: none;
}
.cat__siblings a:hover { border-color: var(--vp-c-brand-1); color: var(--vp-c-brand-1); }

@media (max-width: 560px) {
  .cat__item { grid-template-columns: 5rem minmax(0, 1fr); gap: 0.9rem; }
}
</style>
