#!/usr/bin/env node
// Every browse path the archive offers must exist in the built site.
//
// The 44 keyword paths are generated by dynamic routes, and a dynamic route
// that fails to load is a WARNING in VitePress, not an error: it prints
// `Failed to load …paths.ts`, drops every page that route would have made, and
// exits 0. That is exactly what happened here — a bare relative specifier
// (`.vitepress/…` rather than `./.vitepress/…`, and a leading dot is not the
// same as a leading `./`) silently removed all thirteen one-word listings in
// all three languages. 135 pages instead of 148, and a green build.
//
// So the count is checked against the archive rather than trusted.
//
// Usage: node scripts/check-browse.mjs [distDir]

import { access, readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { shelf, paths, ordered, SHOWN, unreachable } from './lib/browse.mjs'

const dist = process.argv[2] ?? 'docs/.vitepress/dist'
const LOCALES = ['', 'bg', 'de']

const state = await shelf()
const wanted = paths(state)
const problems = []

for (const p of wanted) {
  for (const locale of LOCALES) {
    const file = join(dist, locale, `${p.want.join('/')}.html`)
    try {
      await access(file)
    } catch {
      problems.push(`${locale ? '/' + locale : ''}${p.path} was not built`)
    }
  }
}

// Reachable by a reader, not just by the build. A listing nobody links to is
// the pool with extra steps, which is the state this replaced — so the home
// page of each language must offer the way in.
for (const locale of LOCALES) {
  const home = join(dist, locale, 'index.html')
  let html = ''
  try {
    html = await readFile(home, 'utf8')
  } catch {
    problems.push(`${locale || 'root'}: no home page to check the menu on`)
    continue
  }
  const prefix = locale ? `/${locale}` : ''
  const missing = wanted
    .filter((p) => p.want.length === 1)
    .filter((p) => !html.includes(`href="${prefix}/${p.want[0]}"`))
  if (missing.length) {
    problems.push(
      `${locale || 'root'} home page does not link to ${missing.length} browse path(s): ` +
        missing.map((p) => p.path).join(', ')
    )
  }
}

// The whole point of the surface: no published frame may be unreachable. A
// threshold raised to tidy away thin pages, or a truncation that cuts the
// wrong end, puts frames back in the pool without anybody noticing.
const orphaned = unreachable(state)
if (orphaned.length) {
  problems.push(
    `${orphaned.length} published frame(s) are on no browse path: ${orphaned.slice(0, 8).join(', ')}`
  )
}

if (problems.length) {
  console.error(`check-browse: ${problems.length} problem(s)\n`)
  for (const p of problems.slice(0, 20)) console.error(`  ${p}`)
  if (problems.length > 20) console.error(`  … and ${problems.length - 20} more`)
  process.exit(1)
}

const listed = wanted.reduce((n, p) => n + Math.min(p.frames.length, SHOWN), 0)
console.log(
  `check-browse: ${wanted.length} keyword paths x ${LOCALES.length} languages — ` +
    `${listed} listings, every one of the ${state.frames.length} frames reachable`
)
